### ISSUE TITLE
Some tags just don't work?

### ISSUE THREAD

**Issue by darthnithin** [FujoWebDev/AO3.js#71]
[Harry Potter - J. K. Rowling](https://archiveofourown.org/tags/Harry%20Potter%20-%20J*d*%20K*d*%20Rowling) doesn't work. 
`    const tag = await getTag({
      tagName: "Harry Potter - J. K. Rowling",
    });`

returns 
```
 Error: Category type not found for tag.
    at getTagCategory (file:///C:/Users/__/__/node_modules/@bobaboard/ao3.js/dist/index.js:185:11)
    at getTag (file:///C:/Users/__/__/node_modules/@bobaboard/ao3.js/dist/index.js:238:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///C:/__/__/ao3_tag_graph/test.js:5:17
```
meanwhile other fandoms and tags work, I tested other fandoms, other tags with hyphens, other tags with periods and everything else seems to work but this tag. The HTML and structure of this fandom tag and others seem identical too. I don't know why getTagCategory is failing here.

**Comment by essential-randomness** [comment]
Very curious, will take a look this weekend.

**Comment by essential-randomness** [comment]
I released `@bobaboard/ao3.js@0.17.2` which includes a fix for this. We were only replacing the first instance of special characters. Ooops!
